name: Shellcheck linting

# This is required
on:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pipeline-components/shellcheck:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # This step will also run inside the container
        with:
          submodules: false
      - name: Run ShellCheck
        run: "${GITHUB_WORKSPACE}/.gitlab/shellcheck.bsh"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shellcheck-output
          path: /tmp/results/
